# Generated by Django 2.1.3 on 2023-04-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('NumberOfVisits', models.IntegerField()),
                ('NumberOfLikes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('view', models.IntegerField()),
            ],
        ),
    ]
